SHELL=/bin/rc

all:V:
	go build ./...

fmt:V:
	go fmt ./...

tidy:V: fmt
	go mod tidy -v

vet audit:V:
	go mod verify
	go vet ./...
	go run honnef.co/go/tools/cmd/staticcheck@latest -checks=all,-ST1000,-ST1003,-U1000 ./...
	go run golang.org/x/vuln/cmd/govulncheck@latest ./...

test:V:
	go test ./...

clean:V:
	go clean ./...
